version: '2'

services:
  tws-src:
    container_name: tws-src
    image: busybox
    volumes:
        - ..:/var/www/tws/
  tws-mysqldata:
    container_name: tws-mysqldata
    image: busybox
    volumes:
      - ./mysql/data:/var/lib/mysql/
  tws-nginx:
    image: nginx:latest
    container_name: tws-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - tws-src
    ports:
      - "8080:80"
    depends_on:
      - "tws-src"
      - "tws-php-fpm"
  tws-php-fpm:
    build:
      context: ./php-fpm
    container_name: tws-php-fpm
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes_from:
      - tws-src
    depends_on:
      - "tws-src"
  tws-mysql:
    image: mysql:latest
    container_name: tws-mysql
    ports:
      - "3306:3306"
    volumes_from:
      - tws-mysqldata
    volumes:
      - ./mysql/tws.sql:/tmp/tws.sql:ro
      - ./mysql/init-user-db.sh:/docker-entrypoint-initdb.d/1.init-user-db.sh:ro
    environment:
      - MYSQL_ROOT_PASSWORD=temp123
      - MYSQL_DATABASE=tws
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
volumes:
  tws-src:
  tws-dbdata: